# Generated by Django 3.0.6 on 2020-05-13 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('completed', models.BooleanField(default=False)),
                ('player', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=150)),
                ('points', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('0', 'Not Open'), ('1', 'Answer Time'), ('2', 'Check Answers'), ('3', 'Closed')], default=0, max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Game')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('response', models.CharField(max_length=150)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Round'),
        ),
        migrations.CreateModel(
            name='FinalRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('0', 'Not Open'), ('1', 'Wager'), ('2', 'Answer Time'), ('3', 'Check Answers'), ('4', 'Closed')], default=0, max_length=1)),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('max_wager', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Game')),
            ],
        ),
        migrations.CreateModel(
            name='FinalAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wager', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=200, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('finalround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.FinalRound')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoubleRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.IntegerField(default=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Round')),
            ],
        ),
        migrations.AddConstraint(
            model_name='questionresponse',
            constraint=models.UniqueConstraint(fields=('player', 'question'), name='unique_answer'),
        ),
        migrations.AddConstraint(
            model_name='finalround',
            constraint=models.UniqueConstraint(fields=('game',), name='one_final_round'),
        ),
        migrations.AddConstraint(
            model_name='finalanswer',
            constraint=models.UniqueConstraint(fields=('finalround', 'player'), name='one_final_answer'),
        ),
        migrations.AddConstraint(
            model_name='doubleround',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='unique_double_round'),
        ),
    ]
