# Generated by Django 3.0.6 on 2020-05-15 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia', '0003_question_alt_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('response', models.CharField(max_length=150)),
                ('wager', models.IntegerField(default=None)),
            ],
        ),
        migrations.RenameModel(
            old_name='QuestionResponse',
            new_name='Response',
        ),
        migrations.RenameField(
            model_name='finalround',
            old_name='max_wager',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='round',
        ),
        migrations.AlterField(
            model_name='finalround',
            name='answer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='finalround',
            name='status',
            field=models.CharField(choices=[('0', 'Not Open'), ('1', 'Answer Time'), ('2', 'Check Answers'), ('3', 'Closed')], default=0, max_length=1),
        ),
        migrations.DeleteModel(
            name='FinalAnswer',
        ),
        migrations.AddField(
            model_name='finalresponse',
            name='final_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.FinalRound'),
        ),
        migrations.AddField(
            model_name='finalresponse',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='finalresponse',
            constraint=models.UniqueConstraint(fields=('final_round', 'player'), name='one_final_answer'),
        ),
    ]
