# Generated by Django 3.0.6 on 2020-05-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_auto_20200514_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trivia.Round'),
            preserve_default=False,
        ),
    ]
