# Generated by Django 3.0.6 on 2020-05-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0007_auto_20200517_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleround',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia.Round'),
        ),
    ]
